{% set name = "mpcontribs-client" %}
{% set version = "5.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpcontribs_client-{{ version }}.tar.gz
  sha256: ee2a9aeefe4ea54bfda05ebc6ebde74d9b3707c8cc4efa4fd428852a5a854b19

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - boltons
    - bravado
    - filetype
    - flatten-dict
    - ipython
    - json2html
    - pandas
    - pint
    - plotly
    - pyisemail
    - pymatgen
    - pymongo
    - requests-futures
    - swagger-spec-validator
    - tqdm
    - ujson
    - semantic_version
    - cachetools

test:
  imports:
    - mpcontribs.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/materialsproject/MPContribs/tree/master/mpcontribs-client
  summary: client library for MPContribs API
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fxcoudert
